Centro_Medico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('ingreso.urls')),
    path('', include('web.urls')),
]

ingreso/urls.py
from django.urls import path,include
from . import views
from .views import UserRegisterView, UserLoginView

urlpatterns =[
    path('',views.UsuariosLista, name='usuarios'),
    path('registra/', views.CrearUsuarios, name='registra'),
    path('eliminar/<str:pk>/', views.EliminarUsuarios, name='eliminar'),
    
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('web/', include('web.urls'))
]

web/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'web'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registra/', views.index, name='index'),
    path('home/', views.Registro, name='formulario'),
    path('lista/', views.lista_usuarios, name='listaUsuarios'),
    path('login/', views.IniciarSesion, name='iniciar_sesion'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ingreso/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    tipoUsuario = models.CharField(max_length=60)
    password = models.CharField(max_length=100)

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.nombre
    

web/models.py
from django.db import models

# Create your models here.

web/forms.py
from django import forms

class UserForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)
    tipoUsuario = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    
    

class LoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)

ingreso/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.permissions import AllowAny
from .models import Users
from .serializer import UsersSerializer

class UserRegisterView(generics.CreateAPIView):
    queryset = Users.objects.all()
    serializer_class = UsersSerializer
    permission_classes = (AllowAny,)
    def perform_create(self, serializer):
        user = serializer.save()
        login(self.request, user)

class UserLoginView(generics.CreateAPIView):
    serializer_class = UsersSerializer
    permission_classes = (AllowAny,)
    def post(self, request, *args, **kwargs):
        username = request.data.get("username")
        password = request.data.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            serializer = self.serializer_class(user)
            return Response(serializer.data)
        else:
            return Response({"error": "Credenciales invalidas"})
        

@api_view(['GET'])
def UsuariosLista(request):
    users = Users.objects.all()
    serializer = UsersSerializer(users, many=True)
    return Response(serializer.data)


@api_view(['POST'])
def CrearUsuarios(request):
    serializer = UsersSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors)


@api_view(['DELETE'])
def EliminarUsuarios(request, pk):
    user = get_object_or_404(Users, id=pk)
    user.delete()
    return Response('Usuario eliminado')

web/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import requests
from rest_framework.utils import json
from .forms import UserForm, LoginForm
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

# Create your views here.
def IniciarSesion(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            # Autenticar al usuario
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('form.html') 
            else:
                form.add_error(None, 'Credenciales incorrectas. Por favor, inténtalo de nuevo.')
    else:
        # Si la solicitud no es POST, mostrar el formulario de inicio de sesión vacío
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


# mostrar inicio
def inicio(request):
    return render(request,'inicio.html')
    
# registrar
def index(request):
    response = requests.get('http://127.0.0.1:8000/usuarios').json()
    return render(request, 'index.html', {
        'response': response
    })
    

# listar usuarios
def lista_usuarios(request):
    # Realiza una solicitud GET a la API de la aplicación 'ingreso'
    response = requests.get('http://127.0.0.1:8000/usuarios')
    # Verifica si la solicitud fue exitosa (código de estado 200)
    if response.status_code == 200:
        usuarios = response.json()
        return render(request, 'listaU.html', {'usuarios': usuarios})
    else:
        # Maneja el caso en que la solicitud no fue exitosa
        return render(request, 'error.html', {'mensaje': 'Error al obtener la lista de usuarios'})
    

# registrar usuarios    
def Registro(request):
    url = "http://127.0.0.1:8000/usuarios/registra/"
    form = UserForm(request.POST or None)
    if form.is_valid():
        nombre = form.cleaned_data.get("nombre")
        apellido = form.cleaned_data.get("apellido")
        email = form.cleaned_data.get("email")
        tipoUsuario = form.cleaned_data.get("tipoUsuario")
        password = form.cleaned_data.get("password")
        print(nombre)
        print(apellido)
        print(email)
        print(tipoUsuario)
        print(password)
        data = {'nombre': nombre, 'apellido': apellido, 'email': email, 'tipoUsuario': tipoUsuario, 'password': password}
        headers = {'Content-type': 'application/json', }
        response = requests.post(url, data=json.dumps(data), headers=headers)
        
        # Autenticar y logear al usuario si el registro en el servidor externo fue exitoso
        if response.status_code == 200:  # Ajusta según la lógica específica de tu servidor
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            
        return render(request, 'form.html', {
            'response': response
        })

web/templates/form.html
{% load static %}
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href='{% static "css/stilo2.css" %}' type="text/css"/>
</head>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formulario enviado</title>
</head>
<body>
    <div class="container">
        <div class="column">
            <div class="tit">
                <img src="https://i.postimg.cc/DyQPd7FY/medCent.png" alt="" width="270px">
                <p class="titulo">Centro medico galenos</p>
            </div>
            <div class="tit">
                <a class="titulo"> <i class="material-icons">home</i> Home</>
            </div>
            <div class="tit">
                <a class="titulo"> <i class="material-icons">date_range</i> Agenda</>
            </div>
            <div class="tit">
                <a href="{% url 'web:listaUsuarios'%}" class="titulo"> <i class="material-icons">person</i> Pacientes</>
            </div>
            <br>
            <div class="container2">
                <button class="boton">
                    <a class="link" href="{% url 'web:inicio'%}">Volver al home</a></button>
            </div>
        </div>
        <div class="column2">
            <img src="https://i.postimg.cc/tTvz6JNK/img.png" alt="">
        </div>
    </div>
</body>
</html>

web/templates/index.html
{% load static %}
<head>
    <link rel="stylesheet" href='{% static "css/stilos.css" %}' type="text/css"/>
</head>
<h2 class="title">Centro medico galenos</h2>
<div class="container">
    <h1 class="text">Registrate</h1>
    <form action="{% url 'web:formulario' %}" method="post" class="registration-form">
        {% csrf_token %}
        {{ form.as_p }}
    
        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
        </div>
    
        <div class="form-group">
            <label for="id_apellido">Apellido:</label>
            <input id="id_apellido" type="text" name="apellido" maxlength="100" required>
        </div>
    
        <div class="form-group">
            <label for="id_email">Correo:</label>
            <input id="id_email" type="email" name="email" maxlength="100" required>
        </div>
    
        <div class="form-group">
            <label for="id_tipoUsuario">Tipo de usuario:</label>
            <input id="id_tipoUsuario" type="text" name="tipoUsuario" maxlength="100" required>
        </div>
    
        <div class="form-group">
            <label for="id_password">Contraseña:</label>
            <input id="id_password" type="password" name="password" maxlength="100" required>
        </div>
    
        <button type="submit">Registrar</button>
    </form>
</div>

web/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "css/estilo.css" %}' type="text/css"/>
    <title>Document</title>
</head>
<body>
    <h2 class="title">Centro medico galenos</h2>
    <div class="container" >
        <div class="column">
            <h1 class="text">SU SALUD EN <br >NUESTRAS MANOS</h1>
            <div class="column">
                <!-- <button class="boton">
                    <a class="link" href="{% url 'web:iniciar_sesion' %}">Iniciar sesión</a>
                </button> -->
                <button class="boton">
                    <a class="link" href="{% url 'web:index' %}">Crear Cuenta</a>
                </button>
            </div>
        </div>
        <div class="column">
            <img src='https://i.postimg.cc/bNnYtbwh/centro-MEd.webp' width="450" height="450" alt="" class="img">
        </div>
    </div>
</body>
</html>

web/templates/listaU.html
<!-- web/templates/web/lista_usuarios_web.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Usuarios Web</title>
</head>
<body>
    <h2>Lista de Usuarios desde la Aplicación Ingreso</h2>
    <ul>
        {% for usuario in usuarios %}
            <li>{{ usuario.nombre }} <br> {{ usuario.email }} </li>
        {% endfor %}
    </ul>
</body>
</html>

web/templates/login.html
{% load static %}
<head>
    <link rel="stylesheet" href='{% static "css/estilos.css" %}' type="text/css"/>
</head>
<h2>Inicio Sesión</h2>
<div class="container">
    <form method="post" action="{% url 'web:iniciar_sesion' %}" class="login-form ">
        {% csrf_token %}
        <div>
            <label for="id_username">Correo:</label>
            <input type="text" name="username" required>
        </div>
        <div>
            <label for="id_password">Contraseña:</label>
            <input type="password" name="password" required>
        </div>
        <button type="submit">Iniciar sesión</button>
    </form>
</div>